# Generated by Django 3.2.9 on 2022-05-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
